name: prod-stage-test-typescript

on:
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Release System
      uses: ./.github/actions/release-system-test-typescript
      with:
        working-directory: system-test-typescript