name: qa-stage-java

on:
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/java-test-template.yml
    with:
      stage: "qa"
      deploy-step-name: "Release System"
      run-acceptance-tests: false
      run-e2e-tests: false