name: qa-stage-test-dotnet

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Release System and Run Tests
      uses: ./.github/actions/release-system-test-dotnet
      with:
        working-directory: system-test-dotnet