name: release-stage-test-typescript

on:
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: system-test-typescript

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Release System
      uses: ./.github/actions/release-system
      with:
        working-directory: system-test-typescript

    - name: Setup TypeScript Environment
      uses: ./.github/actions/setup-typescript-environment
      with:
        working-directory: system-test-typescript
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: system-test-typescript/package-lock.json
        run-build: false
        install-playwright: true

    - name: Test
      run: npm test