name: release-stage-monolith-java

on:
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: system-test/java

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Release System
      run: docker compose -f docker-compose.monolith-java.yml up -d
      working-directory: ./
      # NOTE: In real life applications, you'd be deploying your System to some Environment
      # For this demo application, I'm using Docker Compose

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0

    - name: Make Gradle Wrapper executable
      run: chmod +x ./gradlew

    - name: Run Smoke Tests
      run: ./gradlew test --tests com.optivem.eshop.smoketest.*